import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    addNoteButton: {
        alignItems: "center",
        backgroundColor: "navy",
        borderColor: "white",
        borderRadius: 10,
        borderWidth: 2,
        elevation: 6,
        justifyContent: "center",
        padding: 6,
        shadowColor: "rgba(46, 229, 157, 0.4)",
        shadowOpacity: 0.8,
        shadowOffset: { width: 1, height: 13 },
    },
    addNoteContainer: {
        borderRadius: 10,
        flexDirection: "row",
        marginBottom: 20,
        marginHorizontal: 10,
    },
    background: {
        backgroundColor: "turquoise",
        flex: 1,
        justifyContent: "center",
    },
    brand: {
        color: "white",
        borderColor: "white",
        fontSize: 50,
        fontWeight: "bold",
        justifyContent: "center",
        textAlign: "center",
    },
    button: {
        alignItems: "center",
        backgroundColor: "navy",
        borderColor: "lightblue",
        borderRadius: 10,
        borderWidth: 2,
        elevation: 6,
        justifyContent: "center",
        marginHorizontal: 60,
        padding: 6,
        shadowColor: "rgba(46, 229, 157, 0.4)",
        shadowOpacity: 0.8,
        shadowOffset: { width: 1, height: 13 },
    },
    buttonText: {
        color: "white",
        fontSize: 20,
        fontWeight: "bold",
    },
    chatBackButton: {
        alignContent: "center",
        flex: 1,
        justifyContent: "center",
        //backgroundColor: "yellow",
    },
    chatBottomBanner: {
        backgroundColor: "grey",
        borderRadius: 20,
        flexDirection: "row",
        padding: 10,
    },
    chatFriendMessage: {
        backgroundColor: "#ECECEC",
        alignSelf: "flex-start",
    },
    chatInput: {
        flex: 1,
        borderColor: "#ccc",
        borderWidth: 1,
        borderRadius: 20,
        paddingHorizontal: 10,
        marginRight: 10,
    },
    chatMessagesContainer: {
        flexGrow: 1,
        justifyContent: "flex-end",
    },
    chatMessageItem: {
        padding: 10,
        marginVertical: 5,
        marginHorizontal: 10,
        borderRadius: 10,
    },
    chatMyMessage: {
        backgroundColor: "#DCF8C6",
        alignSelf: "flex-end",
    },
    chatName: {
        flex: 8,
        fontSize: 30,
        fontWeight: "bold",
        textAlign: "center",
        //backgroundColor: "green",
    },
    chatTimestamp: {
        fontSize: 5,
        textAlign: "right",
    },
    chatTopBanner: {
        backgroundColor: "grey",
        flexDirection: "row",
        padding: 10,
    },
    delButton: {
        aspectRatio: 1,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        right: 5,
        top: 3,
    },
    flashcard: {
        width: "80%",
        aspectRatio: 1.5,
        backgroundColor: "white",
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "black",
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 3,
        marginBottom: 20,
    },
    flashcardContainer: {
        marginBottom: 10,
        alignItems: "center",
    },
    formBackground: {
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: 10,
        padding: 10,
    },
    friendContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 10,
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 10,
        marginVertical: 5,
        width: "100%",
        backgroundColor: "white",
    },
    friendListContainer: {
        margin: 10,
    },
    image: {
        flex: 1,
        justifyContent: "center",
    },
    materialsContainer: {
        backgroundColor: "lightcyan",
        borderRadius: 10,
        marginHorizontal: 40,
        marginVertical: 10,
        padding: 12,
    },
    nextPrevContainer: {
        flexDirection: "row",
        justifyContent: "space-evenly",
    },
    noteInput: {
        flex: 1,
        backgroundColor: "white",
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        color: "black",
        padding: 10,
        marginRight: 10,
    },
    notesList: {
        flex: 1,
        marginTop: 10,
    },
    noteItem: {
        backgroundColor: "white",
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        flexDirection: "row",
        padding: 1,
        marginBottom: 10,
        marginHorizontal: 10,
    },
    noteText: {
        color: "black",
        flex: 8,
        padding: 10,
    },
    profileBackground: {
        backgroundColor: "white",
        borderRadius: 10,
        marginHorizontal: 30,
        paddingHorizontal: 20,
        paddingVertical: 10,
        justifyContent: "center",
    },
    profileText: {
        color: "black",
        fontSize: 24,
        textAlign: "left",
    },
    quizAnswerText: {
        borderRadius: 5,
        color: "green",
        padding: 5,
        alignSelf: "center",
        fontSize: 16,
        fontWeight: "bold",
    },
    quizOptionContainer: {
        borderRadius: 5,
        borderWidth: 2,
        color: "black",
        marginTop: 15,
    },
    quizOptionText: {
        borderRadius: 5,
        color: "black",
        padding: 5,
        alignSelf: "center",
        fontSize: 16,
    },
    quizQuestionContainer: {
        backgroundColor: "lightcyan",
        borderRadius: 10,
        margin: 10,
        padding: 15,
    },
    quizQuestionText: {
        color: "black",
        fontSize: 20,
        textAlign: "center",
    },
    quizResultStyle: {
        alignSelf: "center",
        color: "black",
        fontSize: 20,
        fontWeight: "bold",
    },
    resultContainer: {
        backgroundColor: "lightcyan",
        borderRadius: 10,
        marginHorizontal: 40,
        padding: 12,
    },
    sendButton: {
        alignItems: "center",
        backgroundColor: "navy",
        borderColor: "lightblue",
        borderRadius: 10,
        borderWidth: 2,
        elevation: 6,
        justifyContent: "center",
        padding: 6,
        shadowColor: "rgba(46, 229, 157, 0.4)",
        shadowOpacity: 0.8,
        shadowOffset: { width: 1, height: 13 },
    },
    textInput: {
        backgroundColor: "white",
        borderColor: "#ccc",
        borderRadius: 5,
        borderWidth: 2,
        color: "black",
        marginHorizontal: 10,
        padding: 10,
    },
    textOutput: {
        color: "black",
        fontWeight: "bold",
        fontSize: 24,
        textAlign: "center",
    },
    usernameText: {
        color: "black",
        fontSize: 16,
        fontWeight: "bold",
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: "center",
        padding: 20,
    },
    switchContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginVertical: 10,
        marginHorizontal: 20,
    },
    radioButtonContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 5,
    },
    radioButton: {
        height: 20,
        width: 20,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "black",
        marginHorizontal: 10,
    },
    radioButtonSelected: {
        backgroundColor: "black",
    },
    checkboxContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 5,
    },
    checkbox: {
        height: 20,
        width: 20,
        borderWidth: 1,
        borderColor: "black",
        marginHorizontal: 10,
    },
    checkboxSelected: {
        backgroundColor: "black",
    },
    card: {
        backgroundColor: "#f9f9f9",
        borderRadius: 8,
        padding: 15,
        marginVertical: 10,
        marginHorizontal: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    title: {
        color: "black",
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 5,
    },
    description: {
        fontSize: 14,
        color: "#444",
        marginBottom: 5,
    },
    dueDate: {
        fontSize: 16,
        color: "#777",
        marginBottom: 10,
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    smallButtonDelete: {
        backgroundColor: "red",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
        marginHorizontal: 5,
    },
    smallButtonComplete: {
        backgroundColor: "green",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
        marginHorizontal: 5,
    },
    smallButtonText: {
        color: "#fff",
        fontSize: 12,
    },
});

export default styles;
