server:
  port: 9080

spring:
  application:
    name: gradleTest
  datasource:
    url: jdbc:mysql://localhost:3306/gradleTest
    username: testUser
    password: Password123

logging:
  level:
    org:
      springframework:
        security: TRACE

security:
  jwt:
    secret-key: woworbitalissomuchworkandsotimeconsumingbutatthesametimeitssofunilovestudysphere
